name: Opos

on:
  schedule:
    # Se ejecuta cada 30 minutos
    - cron:  '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASSWORD }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests
        pip install beautifulsoup4
        pip install python-dotenv
        # Instala cualquier otra dependencia aquí

    - name: Run script
      run: python main.py

